swagger: "2.0"
info:
  description: "This is API for controlling RGB LEDs."
  version: "1.0.0"
  title: "LED Control API"
tags:
- name: "led"
  description: "Accessing the LED"
paths:
  /led:
    post:
      tags:
      - "led"
      summary: "Updates LED status"
      description: "Updates RGB led level values that define color. After update it returns posted led color levels."
      operationId: "changeColor"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Color"
      responses:
        "200":
          description: "Operation Successfull. Color levels changed returned."
          schema:
            $ref: "#/definitions/Color"
        "400":
          description: "Invalid data. Levels of the rgb values are not an integer in range 0-100"
        "500":
          description: "Unexpected error."
    get:
      tags:
      - "led"
      summary: "Return current rgb led levels"
      description: "Returns current rgb led levels that define LEDs color."
      operationId: "getColor"
      responses:
        "200":
          description: "Operation Successfull"
          schema:
            $ref: "#/definitions/Color"
        "500":
          description: "Unexpected error."

definitions:
  Color:
    type: "object"
    properties:
      r:
        type: "integer"
        description: "Red level 0-100"
      g:
        type: "integer"
        description: "Green level 0-100"
      b:
        type: "integer"
        description: "Blue level 0-100"
